
Vagrant.configure("2") do |config|
  config.landrush.enabled = true
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "{{ memory }}"
  end
  config.vm.provider "libvirt" do |vb|
	vb.memory = "{{ memory }}"
  end

  config.vm.define "master1" do |master1|
	master1.vm.box = "{{ vagrant_image }}"
	master1.vm.hostname = "master1.vagrant.test"
	master1.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "2048"]
	  v.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end
  config.vm.define "node1" do |node1|
	node1.vm.box = "{{ vagrant_image }}"
	node1.vm.hostname = "node1.vagrant.test"
	node1.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end
  config.vm.define "node2" do |node1|
	node2.vm.box = "{{ vagrant_image }}"
	node2.vm.hostname = "node1.vagrant.test"
	node2.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end
end
